---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: publish_nginx
    image: plugins/gcr
    settings:
      registry: asia.gcr.io
      repo: nodal-wall-248502/docker_compose_nginx_build
      tags: 0.894
      dockerfile: dockerfiles/dockerfile_for_nginx/Dockerfile
      json_key: >
        {
          "type": "service_account",
          "project_id": "nodal-wall-248502",
          "private_key_id": "cb35de86e545214910cdba4f1510d93984f036c8",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNmZ9a+ShOxHAn\n7BDfRMx4mHYxaOrJRv7RteNvoWc6kIpDqLf8vtmQz726iVcZsKvegjsa2W7hLTar\nhUxZSTwnA2fwkYkEyZ6MdCHUA5Y2W+HqE6VfTmB5qHNg9BcgZqFqGmnGcghVJCR6\nYUueu+XGImRzXu6dK4MC209pnpaGtw6I+PEUgkotauSqgQgb3Rpd52aD67YW6L0N\nbf1LEgOGTJI++sFzRMBKYALzCvHyLKGGcV37pX1ED00obSUiu9C5UHhHICBV84aO\nSAgSpdynZoz0TwHBKfZ4lWKW2DO6Y5Mf7OXG2IFw/HGj1FJNU6q6fYrHLJWh3GAy\nNo44ypFrAgMBAAECggEABaPNEcNwKqiVUdAlVEptUHWJUGqxRObaGgICHVcGGwvy\njdy6+bFwtF1dEIBzr5DDXH+LmVER78/fgd5mmsnMpqS/YsWqxoq9qpkRJEL0tftb\n5Xkp2MCkHarEo0oL+VzmtSir9naVRJR5C9///vVuvFqjU84/3iyDZKPVwMtLWIs3\nBmffCpU188ZyC08VXn0QFH8eod4Ua2ZTvLDFLRDXCao26H5Lep1SXr/aBviBcT7E\n1UQGLcoLFZk5/yGooVlo2ZALUB3nZpDSM7zOrl37O61N6XmeO89GJbO//dX1w2GC\n072kyoHpnTVWhmhdfocwunPkMbfg6qDe0ZbNzqvKkQKBgQC+eWshf6BASr6eDiHq\nXzBMVsY+f9GjEd0ES5n5hA/yy5NCVsZmFYJGKFv2BkQ7yqqKUC4dovYMFIhpnOtJ\nk3lnh+MPuw5gMCzNMwFe+yu1xSpC6k1xn3LzWS+n7pZ5M8CwSBo41NuEyKfXRtq4\njPWuOUCMvkxW83Ika5R1iJOhmwKBgQC+T/p9ouH3bfJY21xzYw2CA/O02aKS1x0W\nOpMxF+gseUjQsh3wq/QGa1pJ03hcFsGV1KUftNelFPAwuQR8H7yXIhlhvqTZPNTC\n7rpV96+A6zmh7KFaP2advLJsP9BRK//tXHg1u4SjsYZNmNHzETNPKpa7/clcapbG\nDZO1oJJ0cQKBgHeSFzuXN81EXrcv3gCYMuSpUJfpe3un+hv5LbaiPbTIMTBi8vcg\np4BNU7V1J551Umuze8+k/lqFBUFvfZDZoEvq1RKJ9bNSar2COGkcucrI9Ae/uFAM\nrYewRCdisllxsJO5H6TvksKfiCWvWBykeJIfZLM1vwySlOPiGPdTfoHjAoGAd5sE\nLpmDsmFjAf07KTmDb8bUD0EIL4kKOsItZ5lCzVCcNqz6rBsljjNB10wURKv4lhXC\ngR7CuHlkSvq8mtXHTKSdlxSdvfnBLZGjggvcPQWYfu+cqH9YGqJQ8D9ayOkCO0b2\nNa7YOZiEc5gruruAp6x4d0WUm4RRpb86qdd0s8ECgYEAjSjdguBHgLROnEjGMdcX\nafhj0AUD3gBG55xxD4sedjcXGltLJYeC20lQgLG01tQykUkIsMHHJer/Kt14CtY5\nakwq8b49MD9zWfXE6hrMa1ZV4zto6g5Ao5leXwVsg/PZr7lPf4oQN3TmYJDDgUXD\nueSFDxRMXziAv0epQ3uUDx0=\n-----END PRIVATE KEY-----\n",
          "client_email": "access-storage@nodal-wall-248502.iam.gserviceaccount.com",
          "client_id": "118390695429912362621",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/access-storage%40nodal-wall-248502.iam.gserviceaccount.com"
        }

  - name: k8s_nginx_deployee
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://34.67.240.171
      kubernetes_token: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9kYWwtd2FsbC0yNDg1MDIiLAogICJwcml2YXRlX2tleV9pZCI6ICJkZmMxZjU4YmVhOTg2YmM0MGZjYmE4YzY2ZjY2YmQxN2E5MDViYzdmIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdWdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLUXdnZ1NnQWdFQUFvSUJBUURONlBkbjNvUEpVSVVLXG5VbTZrOWhJRDFTU1hCQ1VPY1dvVlFhb3lRVHNlbmRjUjdIZ2pLK0V5L09KY3V6ZlczZWdCdkRSUXB1OGsrckt2XG55bFFpMFQ2U3pMNy95VDRkU1dTS0s2eHZJMUM2aWlkVGdXdUF6c3krSFEzRkhYRnVid3d3cURIRE9rbUQ2YThKXG5BSS9oYWthaDJnZkJVOG00aTZEbWUyN3BubDhJOTA2OUxlNXJibGNQS0xyenIzajV2NHNRQ1ZtREIxdTJveFZVXG5VSVJNNGM4dXFpSUVQTGF0a29WTWJjSUJjUHU1SDFIK0U4Mit6aXI4SkJQclpUSXp5VU9ISHhoVGxENmQwazJWXG5KN3cxbjlBVjJneWVWU1Arak9pcURoeWkvT2hFVjIvLzFtSFROZ3FpUmZVRlVVL2k1YS9NTHdtam5NcnNwUHZ2XG5zUmtVNytpUEFnTUJBQUVDZ2Y5WnJwNFRIMWRHMTBzYXM4eDlESy9MKzRsMFBObm04SDdEdzFYZGpZdXlTZ3ppXG5RWndSdFlyZ0trUnRIeDJ5OS9PVXplUDdQTG5yNFVUeVM2MVpmTWxFSnVrSmZ4ME9wR2lseFYvVkNBeWhNb3J1XG5VKy8rcWhPQ3VpVEZOWTJ5QzZ2RGhYNG5DYnY3T0V5RUh6cUxjejVRUUNZZ2pkM09Bd0tSWURGdWp3dlZXeGxyXG54S1dzUmo5VDZNMEc5bmRVcVFlM2YweUdmdHNMTkZsempLMXJhTDQ3aHJMZTZiSDh0ZUV6eWlCQjRPb0RSZDlCXG5QakRwNldpb1BGL0FyZzg5S2ozTGljTHNIazZwV2ZOYWZpRmZHQlRjWlJ3S0pNS2t1czZpekMyWlFKV0ozNWpyXG5XTzlVVmNucmR4ZHQ5WWVyYzRXMDNqU0dSMFFPWE5ZZCs2cWZucVVDZ1lFQTZPb0NVZnNLNFRrV3d1T0hTaGV2XG5LTmpnQkRwL2xWTy95cnVuSHNSOWgvbGRYZ3RScTd6UlMrWUY4RTZaK2UrTjl6YmlSa2Jmam5vcXpoY25OdE95XG4yN25CRGlZZ0hrRUpwa3pSc3Z2c2wycVAvdDdqSzNDZGNiaFRYTzdwVnpGVkJhWWFUcXM3VXJnOGxvNFpTWWZHXG5aQjV1MUNrUTdxUExJaTUvWEgveDErc0NnWUVBNGxIQXNUem96eVRyeWtvWlJsRWd4bDlISlFRZmxPN051WmUrXG42WjhuRDhlZmsvNW0zNHZ5NUtaTnowdUN6NGFPTE11RmRMMjVFRXV2dXZNZEh5WXNReWlRYTlqSFp1VUhpUGIxXG5wSVBOdTZSMG1NM0pyVWJJaStxWjRtR1UzbmdoR1ZIVFhvUllsT08yc0RiUXpLazZhQVFaOUVwZWJDbVBlb1RFXG5CdlRFRE8wQ2dZQk4rU2xWc0tsdnhPRHQxYVlSRStTNzAvOEs2MXFTN3pxaDhEaCtnR0ZXQ0JGTnpwUkUzaTFqXG5MMXFGbklySHRYN2RhQzVRUUtITzNPOC9sMWkxYmlIT2xWMGdFM3RsSlhqSmg2WWNPV0ozUG1GK2ZiZW5iMGdHXG5MaU1hVlpFZ2M0OTNHS2h0OWIwaWNETTRZOUhyWDl6MjM0bFMxWHlwcDRQMXFZTlJ3RE9DaVFLQmdHMzA3RnJ3XG5UZWcrZHZUY2xYVU5lNUFGd0lvaWU3bWZZSUo0VUlBdkhBcFZvWm1FczdTT3lSOEFFYlBTYXlhcXFDN3BYdGkrXG5TTWk3RFJFV2h5S1lLRThreVM0c3I0eTFYN2pTeTd2M2NhQm1JV1FRTDVrcFY4eHEyZ01jQi9raWdtcEwwQmNPXG4wLzdhdCtyYlp3ellkNUVMMVJSVWdaV3BoNVV1SmhOL0hqVnRBb0dBUDJsOUM3TG1MTzUzMDdzODR1L2QyM3RyXG5MVzNiZ2d6Q2RUSlNlMXZKNHNqSXlrWmxSVWNyYlByV21xK2Y0WUltRVR0UVNrSytRU1pMcFVPcHNMZG9BNzN2XG5sMDl3dkxKdEpwdmN4c3lOeThPTEZTdFN0ZHl3aHlDOGVpK2hid3BLYytsUHlIL3d2ay8ydmFtQ3YxMGZXTGVjXG5zbmFXQnRya1d1ODRtdVM1ZGNvPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImFjY2Vzcy1na2VAbm9kYWwtd2FsbC0yNDg1MDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA5MTMwNTU3OTU1NzY0NTM5MTU0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9hY2Nlc3MtZ2tlJTQwbm9kYWwtd2FsbC0yNDg1MDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K
      namespace: default
      deployment: nginx-1
      repo: asia.gcr.io/nodal-wall-248502/docker_compose_nginx_build
      container: docker-compose-nginx-build-sha256-1
      tag: 0.894


  - name: publish_php
    image: plugins/gcr
    settings:
      registry: asia.gcr.io
      repo: nodal-wall-248502/docker_compose_php73_laravel_build
      tags: 0.894
      dockerfile: dockerfiles/dockerfile_for_laravel/Dockerfile
      json_key: >
        {
          "type": "service_account",
          "project_id": "nodal-wall-248502",
          "private_key_id": "cb35de86e545214910cdba4f1510d93984f036c8",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNmZ9a+ShOxHAn\n7BDfRMx4mHYxaOrJRv7RteNvoWc6kIpDqLf8vtmQz726iVcZsKvegjsa2W7hLTar\nhUxZSTwnA2fwkYkEyZ6MdCHUA5Y2W+HqE6VfTmB5qHNg9BcgZqFqGmnGcghVJCR6\nYUueu+XGImRzXu6dK4MC209pnpaGtw6I+PEUgkotauSqgQgb3Rpd52aD67YW6L0N\nbf1LEgOGTJI++sFzRMBKYALzCvHyLKGGcV37pX1ED00obSUiu9C5UHhHICBV84aO\nSAgSpdynZoz0TwHBKfZ4lWKW2DO6Y5Mf7OXG2IFw/HGj1FJNU6q6fYrHLJWh3GAy\nNo44ypFrAgMBAAECggEABaPNEcNwKqiVUdAlVEptUHWJUGqxRObaGgICHVcGGwvy\njdy6+bFwtF1dEIBzr5DDXH+LmVER78/fgd5mmsnMpqS/YsWqxoq9qpkRJEL0tftb\n5Xkp2MCkHarEo0oL+VzmtSir9naVRJR5C9///vVuvFqjU84/3iyDZKPVwMtLWIs3\nBmffCpU188ZyC08VXn0QFH8eod4Ua2ZTvLDFLRDXCao26H5Lep1SXr/aBviBcT7E\n1UQGLcoLFZk5/yGooVlo2ZALUB3nZpDSM7zOrl37O61N6XmeO89GJbO//dX1w2GC\n072kyoHpnTVWhmhdfocwunPkMbfg6qDe0ZbNzqvKkQKBgQC+eWshf6BASr6eDiHq\nXzBMVsY+f9GjEd0ES5n5hA/yy5NCVsZmFYJGKFv2BkQ7yqqKUC4dovYMFIhpnOtJ\nk3lnh+MPuw5gMCzNMwFe+yu1xSpC6k1xn3LzWS+n7pZ5M8CwSBo41NuEyKfXRtq4\njPWuOUCMvkxW83Ika5R1iJOhmwKBgQC+T/p9ouH3bfJY21xzYw2CA/O02aKS1x0W\nOpMxF+gseUjQsh3wq/QGa1pJ03hcFsGV1KUftNelFPAwuQR8H7yXIhlhvqTZPNTC\n7rpV96+A6zmh7KFaP2advLJsP9BRK//tXHg1u4SjsYZNmNHzETNPKpa7/clcapbG\nDZO1oJJ0cQKBgHeSFzuXN81EXrcv3gCYMuSpUJfpe3un+hv5LbaiPbTIMTBi8vcg\np4BNU7V1J551Umuze8+k/lqFBUFvfZDZoEvq1RKJ9bNSar2COGkcucrI9Ae/uFAM\nrYewRCdisllxsJO5H6TvksKfiCWvWBykeJIfZLM1vwySlOPiGPdTfoHjAoGAd5sE\nLpmDsmFjAf07KTmDb8bUD0EIL4kKOsItZ5lCzVCcNqz6rBsljjNB10wURKv4lhXC\ngR7CuHlkSvq8mtXHTKSdlxSdvfnBLZGjggvcPQWYfu+cqH9YGqJQ8D9ayOkCO0b2\nNa7YOZiEc5gruruAp6x4d0WUm4RRpb86qdd0s8ECgYEAjSjdguBHgLROnEjGMdcX\nafhj0AUD3gBG55xxD4sedjcXGltLJYeC20lQgLG01tQykUkIsMHHJer/Kt14CtY5\nakwq8b49MD9zWfXE6hrMa1ZV4zto6g5Ao5leXwVsg/PZr7lPf4oQN3TmYJDDgUXD\nueSFDxRMXziAv0epQ3uUDx0=\n-----END PRIVATE KEY-----\n",
          "client_email": "access-storage@nodal-wall-248502.iam.gserviceaccount.com",
          "client_id": "118390695429912362621",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/access-storage%40nodal-wall-248502.iam.gserviceaccount.com"
        }

  - name: k8s_php73_deployee
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://34.67.240.171
      kubernetes_token: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9kYWwtd2FsbC0yNDg1MDIiLAogICJwcml2YXRlX2tleV9pZCI6ICJkZmMxZjU4YmVhOTg2YmM0MGZjYmE4YzY2ZjY2YmQxN2E5MDViYzdmIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdWdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLUXdnZ1NnQWdFQUFvSUJBUURONlBkbjNvUEpVSVVLXG5VbTZrOWhJRDFTU1hCQ1VPY1dvVlFhb3lRVHNlbmRjUjdIZ2pLK0V5L09KY3V6ZlczZWdCdkRSUXB1OGsrckt2XG55bFFpMFQ2U3pMNy95VDRkU1dTS0s2eHZJMUM2aWlkVGdXdUF6c3krSFEzRkhYRnVid3d3cURIRE9rbUQ2YThKXG5BSS9oYWthaDJnZkJVOG00aTZEbWUyN3BubDhJOTA2OUxlNXJibGNQS0xyenIzajV2NHNRQ1ZtREIxdTJveFZVXG5VSVJNNGM4dXFpSUVQTGF0a29WTWJjSUJjUHU1SDFIK0U4Mit6aXI4SkJQclpUSXp5VU9ISHhoVGxENmQwazJWXG5KN3cxbjlBVjJneWVWU1Arak9pcURoeWkvT2hFVjIvLzFtSFROZ3FpUmZVRlVVL2k1YS9NTHdtam5NcnNwUHZ2XG5zUmtVNytpUEFnTUJBQUVDZ2Y5WnJwNFRIMWRHMTBzYXM4eDlESy9MKzRsMFBObm04SDdEdzFYZGpZdXlTZ3ppXG5RWndSdFlyZ0trUnRIeDJ5OS9PVXplUDdQTG5yNFVUeVM2MVpmTWxFSnVrSmZ4ME9wR2lseFYvVkNBeWhNb3J1XG5VKy8rcWhPQ3VpVEZOWTJ5QzZ2RGhYNG5DYnY3T0V5RUh6cUxjejVRUUNZZ2pkM09Bd0tSWURGdWp3dlZXeGxyXG54S1dzUmo5VDZNMEc5bmRVcVFlM2YweUdmdHNMTkZsempLMXJhTDQ3aHJMZTZiSDh0ZUV6eWlCQjRPb0RSZDlCXG5QakRwNldpb1BGL0FyZzg5S2ozTGljTHNIazZwV2ZOYWZpRmZHQlRjWlJ3S0pNS2t1czZpekMyWlFKV0ozNWpyXG5XTzlVVmNucmR4ZHQ5WWVyYzRXMDNqU0dSMFFPWE5ZZCs2cWZucVVDZ1lFQTZPb0NVZnNLNFRrV3d1T0hTaGV2XG5LTmpnQkRwL2xWTy95cnVuSHNSOWgvbGRYZ3RScTd6UlMrWUY4RTZaK2UrTjl6YmlSa2Jmam5vcXpoY25OdE95XG4yN25CRGlZZ0hrRUpwa3pSc3Z2c2wycVAvdDdqSzNDZGNiaFRYTzdwVnpGVkJhWWFUcXM3VXJnOGxvNFpTWWZHXG5aQjV1MUNrUTdxUExJaTUvWEgveDErc0NnWUVBNGxIQXNUem96eVRyeWtvWlJsRWd4bDlISlFRZmxPN051WmUrXG42WjhuRDhlZmsvNW0zNHZ5NUtaTnowdUN6NGFPTE11RmRMMjVFRXV2dXZNZEh5WXNReWlRYTlqSFp1VUhpUGIxXG5wSVBOdTZSMG1NM0pyVWJJaStxWjRtR1UzbmdoR1ZIVFhvUllsT08yc0RiUXpLazZhQVFaOUVwZWJDbVBlb1RFXG5CdlRFRE8wQ2dZQk4rU2xWc0tsdnhPRHQxYVlSRStTNzAvOEs2MXFTN3pxaDhEaCtnR0ZXQ0JGTnpwUkUzaTFqXG5MMXFGbklySHRYN2RhQzVRUUtITzNPOC9sMWkxYmlIT2xWMGdFM3RsSlhqSmg2WWNPV0ozUG1GK2ZiZW5iMGdHXG5MaU1hVlpFZ2M0OTNHS2h0OWIwaWNETTRZOUhyWDl6MjM0bFMxWHlwcDRQMXFZTlJ3RE9DaVFLQmdHMzA3RnJ3XG5UZWcrZHZUY2xYVU5lNUFGd0lvaWU3bWZZSUo0VUlBdkhBcFZvWm1FczdTT3lSOEFFYlBTYXlhcXFDN3BYdGkrXG5TTWk3RFJFV2h5S1lLRThreVM0c3I0eTFYN2pTeTd2M2NhQm1JV1FRTDVrcFY4eHEyZ01jQi9raWdtcEwwQmNPXG4wLzdhdCtyYlp3ellkNUVMMVJSVWdaV3BoNVV1SmhOL0hqVnRBb0dBUDJsOUM3TG1MTzUzMDdzODR1L2QyM3RyXG5MVzNiZ2d6Q2RUSlNlMXZKNHNqSXlrWmxSVWNyYlByV21xK2Y0WUltRVR0UVNrSytRU1pMcFVPcHNMZG9BNzN2XG5sMDl3dkxKdEpwdmN4c3lOeThPTEZTdFN0ZHl3aHlDOGVpK2hid3BLYytsUHlIL3d2ay8ydmFtQ3YxMGZXTGVjXG5zbmFXQnRya1d1ODRtdVM1ZGNvPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImFjY2Vzcy1na2VAbm9kYWwtd2FsbC0yNDg1MDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA5MTMwNTU3OTU1NzY0NTM5MTU0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9hY2Nlc3MtZ2tlJTQwbm9kYWwtd2FsbC0yNDg1MDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K
      namespace: default
      deployment: php73-fpm
      repo: asia.gcr.io/nodal-wall-248502/docker_compose_php73_laravel_build
      container: docker-compose-php73-laravel-build-sha256-1
      tag: 0.894


#
#- name: ssh-git-pull
#  pull: if-not-exists
#  image: appleboy/drone-ssh
#  environment:
#    ENV:
#      from_secret: env
#  settings:
#    host: 35.229.238.232
#    username: alvin
#    port: 22
#    key:
#      from_secret: privateKey
#    envs: [ENV]
#    script:
#      - cd /var/www/html/laravel_drone_test
#      - sudo git pull
#      - echo $${ENV}
#      - echo $${ENV} | sudo tee .env


#- name: build-nginx-image
#  pull: if-not-exists
#  image: plugins/docker
#  settings:
#    registry: registry.hub.docker.com
#    repo: registry.hub.docker.com/virtualorz/docker_compose_nginx_build
#    dockerfile: dockerfiles/dockerfile_for_nginx/Dockerfile
#    auto_tag: true
#    username: virtualorz
#    password: 2uxirgil

#- name: build-php-image
#  pull: if-not-exists
#  image: plugins/docker
#  settings:
#    registry: registry.hub.docker.com
#    repo: registry.hub.docker.com/virtualorz/dev_compose_php73_laravel_build
#    dockerfile: dockerfiles/dockerfile_for_laravel/Dockerfile
#    auto_tag: true
#    username: virtualorz
#    password: 2uxirgil
