---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: publish_nginx
    image: plugins/gcr
    settings:
      registry: asia.gcr.io
      repo: nodal-wall-248502/docker_compose_nginx_build
      tags: latest
      dockerfile: dockerfiles/dockerfile_for_nginx/Dockerfile
      json_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9kYWwtd2FsbC0yNDg1MDIiLAogICJwcml2YXRlX2tleV9pZCI6ICI0MTAwMjIxZDIyODk5MTFiMTlmYTkyZWNkZTQ1ZjQzYTA0Y2UxOTljIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUR6R1JsL3lweE1ZTnpJXG5hci8vazFVU2E0YnA5dmtzQU50eHNUQlJ6WXVsS0VRV0ptVUtwZnFmYTE4UDl0Zmk3NG5ia0ZDbExMOHN0S1REXG4xY1RneUJ3Q2lReVpQUHVaNkJvSm5CbEo0VDVXNmU2NzdaQTExMWhyN0EwVVJnelNJSnVNQko1RDVsUm1LQmlQXG44MlE1K1UwbEJOZTNmcmhrWmwyZ0FMTTlDY2w2ZUpNRkJJeDdBb2l3STZhYmJUSjFyVHY3akswTjlPSXVxQmhWXG5tRjBQYTdGcFFrNWNIdWZ5QmhHN0tRdXB6dDRZbW5rMVkxYjhWOHN1RFB6S3UxT0REeUpaMGZTVUEyVUlZNkJRXG5CYUhlaUlSOEx0bGI2MU9TNTc5Y2w0a2JYMGVSOVdwc21MY3ArVllUZVF6WjU1am5XekVQV1o5aUhvT1owY0dFXG5DRUFXMC9HWkFnTUJBQUVDZ2dFQUdVaWZ4SkVONHdyREE4eElobHdzUWJOeHo0VTZvcmMvRzZyT1ovK3RHY01mXG5tNzhvREt5NUxab0ZBOXZNVmVQTWpvdkt1M2MxTmdEZXp5aDladFNoUnlrNmFIaTFnV3NveEIyYWFycjAyU1RSXG5DZlk2Sk1OdVJLRkROZnZZS3dXdHIra3VEY2xYdDExTnVyRVptRWNEM1VrTTU1NlVMb3NRQzB0dldQYWE0RFFVXG56YXNSMGtDaW0wMy9jYTRBUTNneHJoWTU4OTI3bTRtZW01MHVQeng1eE84bkZUT08rWHNBbGNieDRtYmpNTWNGXG40MjVGbXljaEVLTVVqWnpyTkZLMURRbWR0OVR4RVFlNDNtY2xHNm1OYWk0dDd4RWhlUk44N3lQaC9hOTBnQWVxXG5iZnVKMkY5dUNBalA3bklPNUNSS0VqYnIvMG9KR1MxZEtlWUs5V1BPZ1FLQmdRRCtHOXJZQjlZRi9DVTJPcnZ2XG4wLzAvSUkzS0tGa1ZUbndZSTVEamZvaSs5dXhrVXU5dXRJL3R0RkVtcE95TmJ2cjArYmpCaThyWDMrMmtpZEhOXG44ZjRiRDFCdElHZFdBNERjUlpOSUhQbFZQclBzNi9DSEpGTURwWCt6TC9PUnVodnc5c1FQblVFYzRpUkZxNlhyXG5sSlovL1h6eU0yeDVHTStiWWFlQW5RK0J3UUtCZ1FEMDZFUXNmVjlQNWxOL055OHNYSGlPa1RmRDc5T2NoMzJVXG5SQWJ2ZlZrdFlKN3htWXFCZ3JmUkRWbFpQSTF6Yk5HM0RNSzQ2bFNwb0dMaWFRWkNpOFBPVmVoaExGdDkrVXhFXG5uM2s3aWdHTEsvVEdJM1JKR3VVMzJ5ZXVETXJkTzJFcFFFWncyYzRZUVp2V2QxcFVoVnhTUVphV0s2NG1FQ0dlXG5XdEdjNzFJMTJRS0JnQkEvK2NPODVJdm5idjNEemNidGVKRno1SDFjRFM1V29ZcnRvMU5aQVNldEpMclpydVFXXG5lZW5La1RIMmRBWXJaYk1LMFN6WFlyWmhaSklVR2kyZ1h3NmQ4UmU1YmNKTFlRODFCOUVod1RRWldXbzZRRngwXG5EemI1ZTJ3YkVlbHN6R0toZFRKR2JTYUtzNlVjNy9SYndUQVlKc2hhVDRLQytxdkdGKzhhbkNaQkFvR0JBSkp6XG5Ta0VvZjVSeDhVQkRxYXZuYUJnbzhxWHloaUkyUzN3YjZlSFFuVUVyWkNDcFprL244Uy9Md2NCQkczMElkNmYwXG5zNFNNYkRBN1BxYVJreks4RFUwWHhpeEZzRGgybVlyM3FqRldaM0hueVNtckRlQ2hlcXlhR3ZKVHFBUC9mQ3lFXG55UnEyeEMxeEhsVnpiY3JaTE1ucmVyYzJTNTlyU2c4OTA5YjZyYmlSQW9HQkFKaGdYT2Mza1VXa2pHczliMnRSXG44S2ExMGdUTmpDRFBKS0JwK1hwRjVCOE95a0gwLzd2VVRWRFg4RHAyZnVzNGtWOEVTMHlnNXp0M1pxWVpRMzl6XG4xRFhJMWxPUVMwbWlwMUVFamxwdWNiNlUyRUcxaTJqeGk5Q1NPNlNlMlNQQ2F0K0JYYjdOdnJTcGdtL3BzTWlSXG5tNk5jU09DYVNZUUV1U3hGaldsRnQxalpcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJhY2Nlc3MtZ2NyQG5vZGFsLXdhbGwtMjQ4NTAyLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNTUxMzUzNDg1ODUxNDk2NTM0NiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYWNjZXNzLWdjciU0MG5vZGFsLXdhbGwtMjQ4NTAyLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9
  - name: publish_php
    image: plugins/gcr
    settings:
      registry: asia.gcr.io
      repo: nodal-wall-248502/docker_compose_php73_laravel_build
      tags: latest
      dockerfile: dockerfiles/dockerfile_for_laravel/Dockerfile
      json_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9kYWwtd2FsbC0yNDg1MDIiLAogICJwcml2YXRlX2tleV9pZCI6ICI0MTAwMjIxZDIyODk5MTFiMTlmYTkyZWNkZTQ1ZjQzYTA0Y2UxOTljIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUR6R1JsL3lweE1ZTnpJXG5hci8vazFVU2E0YnA5dmtzQU50eHNUQlJ6WXVsS0VRV0ptVUtwZnFmYTE4UDl0Zmk3NG5ia0ZDbExMOHN0S1REXG4xY1RneUJ3Q2lReVpQUHVaNkJvSm5CbEo0VDVXNmU2NzdaQTExMWhyN0EwVVJnelNJSnVNQko1RDVsUm1LQmlQXG44MlE1K1UwbEJOZTNmcmhrWmwyZ0FMTTlDY2w2ZUpNRkJJeDdBb2l3STZhYmJUSjFyVHY3akswTjlPSXVxQmhWXG5tRjBQYTdGcFFrNWNIdWZ5QmhHN0tRdXB6dDRZbW5rMVkxYjhWOHN1RFB6S3UxT0REeUpaMGZTVUEyVUlZNkJRXG5CYUhlaUlSOEx0bGI2MU9TNTc5Y2w0a2JYMGVSOVdwc21MY3ArVllUZVF6WjU1am5XekVQV1o5aUhvT1owY0dFXG5DRUFXMC9HWkFnTUJBQUVDZ2dFQUdVaWZ4SkVONHdyREE4eElobHdzUWJOeHo0VTZvcmMvRzZyT1ovK3RHY01mXG5tNzhvREt5NUxab0ZBOXZNVmVQTWpvdkt1M2MxTmdEZXp5aDladFNoUnlrNmFIaTFnV3NveEIyYWFycjAyU1RSXG5DZlk2Sk1OdVJLRkROZnZZS3dXdHIra3VEY2xYdDExTnVyRVptRWNEM1VrTTU1NlVMb3NRQzB0dldQYWE0RFFVXG56YXNSMGtDaW0wMy9jYTRBUTNneHJoWTU4OTI3bTRtZW01MHVQeng1eE84bkZUT08rWHNBbGNieDRtYmpNTWNGXG40MjVGbXljaEVLTVVqWnpyTkZLMURRbWR0OVR4RVFlNDNtY2xHNm1OYWk0dDd4RWhlUk44N3lQaC9hOTBnQWVxXG5iZnVKMkY5dUNBalA3bklPNUNSS0VqYnIvMG9KR1MxZEtlWUs5V1BPZ1FLQmdRRCtHOXJZQjlZRi9DVTJPcnZ2XG4wLzAvSUkzS0tGa1ZUbndZSTVEamZvaSs5dXhrVXU5dXRJL3R0RkVtcE95TmJ2cjArYmpCaThyWDMrMmtpZEhOXG44ZjRiRDFCdElHZFdBNERjUlpOSUhQbFZQclBzNi9DSEpGTURwWCt6TC9PUnVodnc5c1FQblVFYzRpUkZxNlhyXG5sSlovL1h6eU0yeDVHTStiWWFlQW5RK0J3UUtCZ1FEMDZFUXNmVjlQNWxOL055OHNYSGlPa1RmRDc5T2NoMzJVXG5SQWJ2ZlZrdFlKN3htWXFCZ3JmUkRWbFpQSTF6Yk5HM0RNSzQ2bFNwb0dMaWFRWkNpOFBPVmVoaExGdDkrVXhFXG5uM2s3aWdHTEsvVEdJM1JKR3VVMzJ5ZXVETXJkTzJFcFFFWncyYzRZUVp2V2QxcFVoVnhTUVphV0s2NG1FQ0dlXG5XdEdjNzFJMTJRS0JnQkEvK2NPODVJdm5idjNEemNidGVKRno1SDFjRFM1V29ZcnRvMU5aQVNldEpMclpydVFXXG5lZW5La1RIMmRBWXJaYk1LMFN6WFlyWmhaSklVR2kyZ1h3NmQ4UmU1YmNKTFlRODFCOUVod1RRWldXbzZRRngwXG5EemI1ZTJ3YkVlbHN6R0toZFRKR2JTYUtzNlVjNy9SYndUQVlKc2hhVDRLQytxdkdGKzhhbkNaQkFvR0JBSkp6XG5Ta0VvZjVSeDhVQkRxYXZuYUJnbzhxWHloaUkyUzN3YjZlSFFuVUVyWkNDcFprL244Uy9Md2NCQkczMElkNmYwXG5zNFNNYkRBN1BxYVJreks4RFUwWHhpeEZzRGgybVlyM3FqRldaM0hueVNtckRlQ2hlcXlhR3ZKVHFBUC9mQ3lFXG55UnEyeEMxeEhsVnpiY3JaTE1ucmVyYzJTNTlyU2c4OTA5YjZyYmlSQW9HQkFKaGdYT2Mza1VXa2pHczliMnRSXG44S2ExMGdUTmpDRFBKS0JwK1hwRjVCOE95a0gwLzd2VVRWRFg4RHAyZnVzNGtWOEVTMHlnNXp0M1pxWVpRMzl6XG4xRFhJMWxPUVMwbWlwMUVFamxwdWNiNlUyRUcxaTJqeGk5Q1NPNlNlMlNQQ2F0K0JYYjdOdnJTcGdtL3BzTWlSXG5tNk5jU09DYVNZUUV1U3hGaldsRnQxalpcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJhY2Nlc3MtZ2NyQG5vZGFsLXdhbGwtMjQ4NTAyLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNTUxMzUzNDg1ODUxNDk2NTM0NiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYWNjZXNzLWdjciU0MG5vZGFsLXdhbGwtMjQ4NTAyLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9

#- name: ssh-git-pull
#  pull: if-not-exists
#  image: appleboy/drone-ssh
#  environment:
#    ENV:
#      from_secret: env
#  settings:
#    host: 35.229.238.232
#    username: alvin
#    port: 22
#    key:
#      from_secret: privateKey
#    envs: [ENV]
#    script:
#      - cd /var/www/html/laravel_drone_test
#      - sudo git pull
#      - echo $${ENV}
#      - echo $${ENV} | sudo tee .env


#- name: build-nginx-image
#  pull: if-not-exists
#  image: plugins/docker
#  settings:
#    registry: registry.hub.docker.com
#    repo: registry.hub.docker.com/virtualorz/docker_compose_nginx_build
#    dockerfile: dockerfiles/dockerfile_for_nginx/Dockerfile
#    auto_tag: true
#    username: virtualorz
#    password: 2uxirgil

#- name: build-php-image
#  pull: if-not-exists
#  image: plugins/docker
#  settings:
#    registry: registry.hub.docker.com
#    repo: registry.hub.docker.com/virtualorz/dev_compose_php73_laravel_build
#    dockerfile: dockerfiles/dockerfile_for_laravel/Dockerfile
#    auto_tag: true
#    username: virtualorz
#    password: 2uxirgil
