---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: build-nginx-image
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: docker.pkg.dockerhub.com
    repo: virtualorz/docker_compose_nginx_build
    dockerfile: dockerfiles/dockerfile_for_nginx/Dockerfile
    auto_tag: true
    username: virtualorz
    password: 2uxirgil

- name: build-php-image
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: docker.pkg.dockerhub.com
    repo: virtualorz/dev_compose_php73_laravel_build
    dockerfile: dockerfiles/dockerfile_for_laravel/Dockerfile
    auto_tag: true
    username: virtualorz
    password: 2uxirgil
